modules:
  - name: server
    symbols:
      - name: s_GameEventManager
        category: gv
        alias:
          - GameEventManager
      - name: CCSPlayer_MovementServices_SetupMove
        category: vfunc
        alias: [SetupMove]
      - name: CCSPlayer_MovementServices_Duck
        category: func
        alias: [Duck]
      - name: CCSPlayer_MovementServices_LadderMove
        category: func
        alias: [LadderMove]
      - name: CCSPlayer_MovementServices_OnJumpLegacy
        category: func
        alias: [OnJumpLegacy]
      - name: CCSPlayer_MovementServices_OnJumpModern
        category: func
        alias: [OnJumpModern]
      - name: CCSPlayer_MovementServices_AirMove
        category: func
        alias: [AirMove]
      - name: CCSPlayer_MovementServices_AirAccelerate
        category: func
        alias: [AirAccelerate]
      - name: CCSPlayer_MovementServices_TryPlayerMove
        category: func
        alias: [TryPlayerMove]
      - name: CCSPlayer_MovementServices_CategorizePosition
        category: func
        alias: [CategorizePosition]
      - name: CBasePlayerController_OnSimulateUserCommands
        category: func
        alias: [PhysicsSimulate]
      - name: CBaseEntity_Teleport
        category: vfunc
        alias: [Teleport]
  - name: engine
    symbols:
      - name: CNetworkGameServer_ClientList
        category: structmember
        struct: CNetworkGameServer
        member: ClientList
        alias: [ClientOffset]
      - name: CServerSideClient_ProcessRespondCvarValue
        category: vfunc
        alias: [ProcessRespondCvarValue]
      - name: CServerSideClientBase_m_nClientSlot
        category: structmember
        struct: CServerSideClientBase
        member: m_nClientSlot
        alias: [ClientSlotOffset]
