func_name: CKeyValuesSystem_GetKeyValuesExpressionSymbol
func_va: '0x1ac580'
func_rva: '0x1ac580'
func_size: '0x480'
func_sig: 48 85 F6 0F 84 ?? ?? ?? ?? 55 31 C0 48 89 E5 41 56
vtable_name: CKeyValuesSystem
vfunc_offset: '0x50'
vfunc_index: 10
