func_name: CSource2GameClients_ClientSettingsChanged
func_va: '0x180de0ec0'
func_rva: '0xde0ec0'
func_size: '0x26'
func_sig: 48 83 EC ?? 8B CA E8 B5 6B ED ??
vtable_name: CSource2GameClients
vfunc_offset: '0x98'
vfunc_index: 19
