import { readFile, readdir } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { canonicalJsonBytes, compareGameVersions, parseLegacyInputs, validateLegacyInputs } from './legacyInputs.mjs'
import { compareGameVersions as tsCompareGameVersions } from './staticAssetPluginUtils'

const fixtureDirectory = resolve(process.cwd(), '..', 'tests', 'fixtures', 'legacy_inputs')
const canonicalDirectory = resolve(process.cwd(), '..', 'tests', 'fixtures', 'canonical_json')

describe('legacy inputs canonical encoding', () => {
  it('matches the reference canonical bytes generated by the toolchain', async () => {
    const source = JSON.parse(await readFile(join(canonicalDirectory, 'canonical_source.json'), 'utf8'))
    const expected = await readFile(join(canonicalDirectory, 'canonical_expected.bin'))
    expect(canonicalJsonBytes(source).equals(expected)).toBe(true)
  })

  it('shares game-version ordering with the Vite plugin comparator', () => {
    const versions = ['14167', '14168b', '14168', '14180', '1417a', '14178b', '1419']
    expect([...versions].sort(compareGameVersions)).toEqual([...versions].sort(tsCompareGameVersions))
    expect([...versions].sort(compareGameVersions)[0]).toBe('14180')
  })
})

describe('legacy inputs manifest validation', () => {
  it('accepts the canonical fixture and rejects every invalid fixture', async () => {
    const names = (await readdir(fixtureDirectory)).filter((name) => name.endsWith('.json')).sort()
    expect(names).toContain('valid.json')
    for (const name of names) {
      const raw = await readFile(join(fixtureDirectory, name))
      if (name === 'valid.json') {
        expect(parseLegacyInputs(raw, name)).toEqual(expect.objectContaining({ schemaVersion: 1 }))
      } else {
        expect(() => parseLegacyInputs(raw, name), name).toThrow()
      }
    }
  })

  it('rejects a structurally valid object with an unknown key', async () => {
    const value = JSON.parse((await readFile(join(fixtureDirectory, 'valid.json'))).toString('utf8'))
    value.extra = 1
    expect(() => validateLegacyInputs(value, 'inline')).toThrow(/expected keys/)
  })

  it('rejects a traversal path in an otherwise valid manifest', async () => {
    const value = JSON.parse((await readFile(join(fixtureDirectory, 'valid.json'))).toString('utf8'))
    value.gamedata.versions[0].files[0].path = 'gamedata/14178b/../escape.jsonc'
    expect(() => validateLegacyInputs(value, 'inline')).toThrow(/unsafe path segment/)
  })
})
