func_name: CGameConfiguration_InitGameSession
func_va: '0x16c3330'
func_rva: '0x16c3330'
func_size: '0x300'
func_sig: 55 48 89 E5 41 57 41 56 41 55 41 54 49 89 FC 53 48 89 F3 BE ?? ?? ?? ?? 48 83 EC ?? 4C 8D 2D ?? ?? ?? ??
vtable_name: CGameConfiguration
vfunc_offset: '0xb0'
vfunc_index: 22
