func_name: CGameConfiguration_ComputeMaxClients
func_va: '0x180be12c0'
func_rva: '0xbe12c0'
func_size: '0x51e'
func_sig: 48 8B C4 48 89 48 ?? 53 48 81 EC ?? ?? ?? ?? 48 89 68 ??
vtable_name: CGameConfiguration
vfunc_offset: '0xa8'
vfunc_index: 21
