func_name: CKeyValuesSystem_GetKeyValuesExpressionSymbol
func_va: '0x1800dffe0'
func_rva: '0xdffe0'
func_size: '0xfb8'
func_sig: 48 89 5C 24 ?? 55 56 57 48 83 EC ?? 48 8B F9
vtable_name: CKeyValuesSystem
vfunc_offset: '0x48'
vfunc_index: 9
