func_name: CServerSideClientBase_UpdateUserSettings
func_va: '0x1800c99d0'
func_rva: '0xc99d0'
func_size: '0xa1'
func_sig: 48 89 5C 24 ?? 57 48 83 EC ?? 48 8B 01 48 8D 15 ?? ?? ?? ?? 48 8B F9 48 8B 89 ?? ?? ?? ??
vtable_name: CServerSideClientBase_vtable
vfunc_offset: '0x1b8'
vfunc_index: 55
